level = "info"
bind = "0.0.0.0:7999"
concurrent_limit = 65535
timeout = 600
connect_timeout = 60
tcp_keepalive = 60
no_keepalive = false
pool_idle_timeout = 90
enable_direct = false
cookie_store = true
disable_webui = false
enable_file_proxy = false
enable_arkose_proxy = false
arkose_gpt3_experiment = false
arkose_gpt3_experiment_solver = false
arkose_solver = "yescaptcha"
tb_enable = false
tb_store_strategy = "mem"
tb_redis_url = "redis://127.0.0.1:6379"
tb_capacity = 60
tb_fill_rate = 1
tb_expired = 86400
pcert = "ca/cert.crt"
pkey = "ca/key.pem"

[[proxies]]

[proxies.all]
proxy = "socks5://127.0.0.1:8888"

[[proxies]]

[proxies.all]
proxy = "http://127.0.0.1:8889/"

[[proxies]]

[proxies.api]
interface = "192.168.1.1"

[[proxies]]

[proxies.api]
ipv6subnet = "2001:db8::/32"
